### ISSUE TITLE
Modal box to take speed parameter as input

### ISSUE THREAD

**Issue by Sumaid** [Sumaid/smart_traffic_analysis#13]
Speed input given by user will be the speed limit which will be considered. 
This will be followed by other model boxes to take other parameters and in the end, make POST api call to flask with parameters.
See existing API calls in input-video component and snapshots component. 
There's a dummy API call in flask called '/api/postparameters', modify it to your use.

**Comment by hellomasaya** [comment]
Finished.
368c827ed5a831a99102da06c6a8a36da5eb13e6
