### ISSUE TITLE
Complete modal boxes workflow

### ISSUE THREAD

**Issue by Sumaid** [Sumaid/smart_traffic_analysis#17]
When user clicks upload button
1) Make GET request to retrieve a frame from video  - `/api/getframe` 
2) Modal boxes to take different parameters
3) Make POST request to give parameters to backend - `/api/postparameters`
4) All this while background should be blurred

**Comment by hellomasaya** [comment]
1, 2 and 4 done

**Comment by hellomasaya** [comment]
3 being handled in Issue #39
