### ISSUE TITLE
Handle Upload/Browse buttons' events when a video is already being processed

### ISSUE THREAD

**Issue by Sumaid** [Sumaid/smart_traffic_analysis#21]
There are two options here : 

1. Disable buttons till entire processing is done. 
2. Let user upload another video, if he does upload a video while another's processing is going on, kill the ongoing feature threads and restart with current video.

**Comment by Sumaid** [comment]
This is part of changing application's status to 'Processing'.

**Comment by hellomasaya** [comment]
Handled in Issue #22
