### ISSUE TITLE
Divide docker-compose file

### ISSUE THREAD

**Issue by hellomasaya** [Sumaid/smart_traffic_analysis#30]
Divide `docker-compose` file for frontend and backend to reduce the slow running time [for backend developers].

**Comment by Sumaid** [comment]
Updated readme to give instruction regarding this. 
If your one part crashes like if backend crashes, then you can simply fix the issue and run `docker-compose restart backend` in a different terminal to get that part running. Similar if frontend crashes, just run `docker-compose restart frontend`.
No need to run `docker-compose up` if you just change one service.
